[tool.poetry]
name = "ismir2017-deepsalience"
version = "0.1.0"
description = "soundBrilliance fork of rabitt/ismir2017-deepsalience"
authors = []

[tool.poetry.dependencies]
python = "3.8.13"
tensorflow = "2.2.3"
pescador = "1.0.0"
librosa = "0.5.0"
mir_eval = "0.4"
joblib = "0.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
